### ISSUE TITLE
worksheetName doesn't accept space or dash in string

### ISSUE THREAD

**Issue by haotuusa** [GrandyB/SheetsIO#40]
**Describe the bug**
If the name of the tab include dash or space, SheetsIO will throw an error after clicking "update now"

**To Reproduce**
1. Go to json file
2. Change worksheetName into any name containing space or dash
3. save json and load the config SheetsIO, then click Update now

**Expected behavior**
Should run smoothly regardless of space of dash

**Screenshots**
if containing space, it throws json error which is not correct, because space is acceptable in json
![Screenshot 2021-04-02 174750](https://user-images.githubusercontent.com/12025033/113404992-a88f0c00-93db-11eb-85ec-a9efaa9392f8.png)

if containing dash it says unable to parse range
![image](https://user-images.githubusercontent.com/12025033/113405183-fe63b400-93db-11eb-9b58-27059a7e7fcd.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by GrandyB** [comment]
Nice catch!
I'll have a look at that now.

**Comment by GrandyB** [comment]
So the two errors...
When SheetsIO requests data from the Google Sheets API it needs the spreadsheet ID, worksheet name and the apiKey; you can also optionally provide it a cell reference "range" (e.g. A4:D4) and only return data from those cells, but SheetsIO just asks for the whole sheet.

Previously, we were taking the worksheet name from config and directly putting it into the URL for the request to Google... but spaces are not automatically handled - we have to do some encoding ourselves to replace " " with "%20", otherwise Google returns a html page giving a vague explanation that a bad request happened. So there's two parts to this - one is that SheetsIO needs to "nicely" handle when json is not returned so that the error is more informative, and we need to properly encode the worksheet name when making a request.

I am currently putting together a new minor version release (v0.7.2) - will add tests for the fix here and release that shortly.

**Comment by GrandyB** [comment]
Addressed in https://github.com/GrandyB/SheetsIO/commit/f80438133f9bf5ebb32530b230384ff42c10bc49

**Comment by GrandyB** [comment]
Released in v0.7.2

https://github.com/GrandyB/SheetsIO/releases/tag/v0.7.2
