### ISSUE TITLE
Is it  possible to customize the text?

### ISSUE THREAD

**Issue by IronDrachen** [GrandyB/SheetsIO#58]
Hello, is it possible to change the text font / size / color once its imported into OBS? 

I got the images working great, but my text shows up small and blurry. 

Thanks!

**Comment by GrandyB** [comment]
The only thing SheetsIO controls is the data in the local txt file that OBS pulls in from. 

The styling of a text source is entirely set on OBS' side - font, size, position, colour etc, so this isn't a SheetsIO issue.

However some OBS advice - instead of clicking & dragging the corner blocks of your text sources to make the text bigger, instead go to the properties of the text source and increase the font size in there until it's the size you want. The corner block method will artificially try to resize what's there, which is fine for images but not ideal for text.

**Comment by IronDrachen** [comment]
Ohhhh, I was trying to access it via the browser . I tried dragging and dropping the txt file into OBS and I see all those options now. 

Awesome this does everything I need it to do. I use OBS for D&D and I wanted a way to show my characters HP and stats during the game. Thanks so much for making this!

**Comment by IronDrachen** [comment]
Closed

**Comment by GrandyB** [comment]
Awesome! That's a fun use case.
